finished
YuriiPohorilets/icecream-project-01 pull request #19
Opened 2022-06-25 18:58 UTC by KupreichukAlex

2022-06-25 19:39 UTC, YuriiPohorilets requested changes

2022-06-25 19:39 UTC, YuriiPohorilets commented on src/sass/components/_gallery.scss
> +                @media screen and (min-width:768px) {
Для медиа правил используй mixin `@include bp(mobile-tablet-desktop);`

2022-06-25 19:39 UTC, YuriiPohorilets commented on src/sass/components/_gallery.scss
>      &__list {
Конкотенацию `&` используй только для псевдоклассов (`:hover`, `:focus` и т.д.) и псеводэлементов (.`::after` `::not()` и т.д.).

2022-06-26 06:03 UTC, KupreichukAlex commented on src/sass/components/_gallery.scss
>      &__list {
конкатенацию использовал вседа так и Иван сказал норм. Ну и в видео репеты , Ярослава такое видел ну и вообще удобно сразу видно что это вложенные элементы блока gallery

2022-06-26 06:21 UTC, KupreichukAlex commented on src/sass/components/_gallery.scss
> +                @media screen and (min-width:768px) {
ok

2022-06-26 10:05 UTC, YuriiPohorilets commented on src/sass/components/_gallery.scss
>      &__list {
С нашего конспекта.
```
Правила вложенности
Вложенность селекторов это отличный способ сэкономить время и упростить поддержку, но чрезмерная вложенность гарантированно вызовет проблемы с читабельностью кода.
Создавайте новое правило для каждого блока или элемента, а вложенности и конкатенации используйте для оформления состояний и BEM-модификаторов. То есть, пользуйтесь здравым смыслом, и делайте так, как удобно, потому что SCSS-код пишется для удобства разработчика.
```
Когда ты сам верстаешь - тебе удобно, ты знаешь, где что. Но на самом деле оно не читабельно. Вложенности для псевдоэлементов/классов и состоянии - ок. Но так не читабельно. И в видео Репета говорил о том же

2022-06-26 10:09 UTC, YuriiPohorilets requested changes

2022-06-26 10:09 UTC, YuriiPohorilets commented on src/sass/components/_gallery.scss
>      &__list {
Я уже проскролил, и не понимаю какого `блока `этот `элемент`:
![image](https://user-images.githubusercontent.com/102477210/175809316-0824630d-b130-43f2-b413-91e29070b735.png)
А представь, что у тебя в секции 5 списков. И в каждом ты `li` задаешь класс `&__item`

2022-06-26 16:57 UTC, YuriiPohorilets approved these changes

2022-06-26 16:57 UTC, merged