products-mobile
YuriiPohorilets/icecream-project-01 pull request #9
Opened 2022-06-24 17:56 UTC by Golub-Alexandr

2022-06-24 18:46 UTC, YuriiPohorilets requested changes

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +	font-weight: bold;
`font-weight: bold;` - не нужно. Достаточно `font-weight: 700;`

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +	margin: auto;
`margin: auto;` - замени на `margin: 0 auto;` или `top, right`

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +.products__title {
Для заголовка используй плейсхолдер `%title`

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +.products__subtitle {
Для подзалоговка плейсхолдер - `%caption `

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +.products__container {
Используй просто класс .container для центрирования и падингов. Тут оставь только `min-max-width`, если необходимо.

2022-06-24 18:46 UTC, YuriiPohorilets commented on src/sass/components/_products.scss
> +	list-style: none;
Плейсхолдер `%list`

2022-06-24 19:29 UTC, Golub-Alexandr commented
Исправил, посмотри пожалуйста.

2022-06-25 07:02 UTC, YuriiPohorilets approved these changes

2022-06-25 07:03 UTC, merged